// Centralized Multilingual UI Dictionary for Verity AI

export const UI_TRANSLATIONS = {
  English: {
    trust_engine: "VERITY AI TRUST ENGINE",
    detected_language: "Detected Language",
    response_language: "Response Language",
    evidence_trust_score: "Evidence Trust Score",
    message_analysis: "Message Analysis",
    original_input: "Original Message",
    why_header: "Why this assessment?",
    why_short: "Why?",
    recommended_action: "What should you do?",
    evidence_and_sources: "Evidence & Sources",
    sources_checked: "checked",
    listen: "Listen",
    stop_voice: "Stop Voice",
    voice_active: "voice active",
    voice_unavailable: "voice unavailable",
    verify_another: "Verify Another Piece of Content",
    topic: "Topic",
    before_you_share_title: "Before You Share",
    supports_claim: "✓ SUPPORTS INFORMATION",
    contradicts_claim: "❌ CONTRADICTS INFORMATION",
    inconclusive_claim: "⚠ RELATED / INCONCLUSIVE",
    no_sources_found: "Insufficient relevant evidence found online for this message.",
    upload_another: "Upload Another Image",
    not_relevant_title: "⚠️ NOT RELEVANT",
    not_relevant_msg: "This content does not appear to contain a meaningful message or information that Verity AI can verify.",
    try_another_btn: "Try Another",
    risk_indicators_title: "Risk Indicators",
    link_check_title: "🔗 Link Check",
    topics: {
      "Health / Medical": "Health / Medical",
      "Weather / Advisory": "Weather / Advisory",
      "Financial Scam / Viral": "Financial Scam / Viral",
      "Education": "Education",
      "Science / Astronomy": "Science / Astronomy",
      "Government / Public Policy": "Government / Public Policy",
      "Entertainment": "Entertainment",
      "Technology / Security": "Technology / Security",
      "General Viral Claim": "General Message",
      "Not Relevant": "Not Relevant"
    }
  },

  Telugu: {
    trust_engine: "వెరిటీ AI ట్రస్ట్ ఇంజిన్",
    detected_language: "గుర్తించిన భాష",
    response_language: "ప్రతిస్పందన భాష",
    evidence_trust_score: "ఆధారాల విశ్వసనీయత స్కోరు",
    message_analysis: "సందేశ విశ్లేషణ",
    original_input: "అసలు సందేశం",
    why_header: "ఈ నిర్ధారణకు కారణం ఏమిటి?",
    why_short: "ఎందుకు?",
    recommended_action: "మీరు ఏమి చేయాలి?",
    evidence_and_sources: "ఆధారాలు మరియు మూలాలు",
    sources_checked: "తనిఖీ చేయబడ్డాయి",
    listen: "వినండి",
    stop_voice: "ఆపండి",
    voice_active: "వాయిస్ అందుబాటులో ఉంది",
    voice_unavailable: "వాయిస్ లభ్యం కాలేదు",
    verify_another: "మరొక సమాచారాన్ని సరిచూడండి",
    topic: "విషయం",
    before_you_share_title: "షేర్ చేయడానికి ముందు (తనిఖీ జాబితా)",
    supports_claim: "✓ ఆధారాలు మద్దతు ఇస్తున్నాయి",
    contradicts_claim: "❌ ఆధారాలు ఖండిస్తున్నాయి",
    inconclusive_claim: "⚠ సంబంధిత సమాచారం / ఇంకా నిర్ధారణ కాలేదు",
    no_sources_found: "ఈ సందేశానికి సంబంధించి ఆన్‌లైన్‌లో తగినన్ని ఆధారాలు లభించలేదు.",
    upload_another: "మరొక చిత్రాన్ని అప్‌లోడ్ చేయండి",
    not_relevant_title: "⚠️ సంబంధం లేనిది",
    not_relevant_msg: "ఈ సమాచారంలో సరిచూడదగిన వార్త లేదా సందేశం కనుగొనబడలేదు.",
    try_another_btn: "మరొకటి ప్రయత్నించండి",
    risk_indicators_title: "ప్రమాద సూచికలు (రిస్క్ సిగ్నల్స్)",
    link_check_title: "🔗 లింక్ తనిఖీ (Link Check)",
    topics: {
      "Health / Medical": "ఆరోగ్యం / వైద్యం",
      "Weather / Advisory": "వాతావరణం / హెచ్చరిక",
      "Financial Scam / Viral": "ఆర్థిక మోసం / వైరల్",
      "Education": "విద్య / విద్యా సంబంధిత",
      "Science / Astronomy": "సైన్స్ / ఖగోళ శాస్త్రం",
      "Government / Public Policy": "ప్రభుత్వం / ప్రజా విధానం",
      "Entertainment": "సినిమా / వినోదం",
      "Technology / Security": "సాంకేతికత / భద్రత",
      "General Viral Claim": "సాధారణ మెసేజ్",
      "Not Relevant": "సంబంధం లేనిది"
    }
  },

  Kannada: {
    trust_engine: "ವೆರಿಟಿ AI ಟ್ರಸ್ಟ್ ಇಂಜಿನ್",
    detected_language: "ಗುರುತಿಸಲಾದ ಭಾಷೆ",
    response_language: "ಪ್ರತಿಕ್ರಿಯೆ ಭಾಷೆ",
    evidence_trust_score: "ಸಾಕ್ಷ್ಯದ ವಿಶ್ವಾಸಾರ್ಹತೆ ಸ್ಕೋರ್",
    message_analysis: "ಸಂದೇಶ ವಿಶ್ಲೇಷಣೆ",
    original_input: "ಮೂಲ ಸಂದೇಶ",
    why_header: "ಈ ಮೌಲ್ಯಮಾಪನಕ್ಕೆ ಕಾರಣವೇನು?",
    why_short: "ಏಕೆ?",
    recommended_action: "ನೀವು ಏನು ಮಾಡಬೇಕು?",
    evidence_and_sources: "ಸಾಕ್ಷ್ಯಗಳು ಮತ್ತು ಮೂಲಗಳು",
    sources_checked: "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    listen: "ಕೇಳಿ",
    stop_voice: "ನಿಲ್ಲಿಸಿ",
    voice_active: "ಧ್ವನಿ ಸಕ್ರಿಯವಾಗಿದೆ",
    voice_unavailable: "ಧ್ವನಿ ಲಭ್ಯವಿಲ್ಲ",
    verify_another: "ಮತ್ತೊಂದು ಮಾಹಿತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ",
    topic: "ವಿಷಯ",
    before_you_share_title: "ಹಂಚಿಕೊಳ್ಳುವ ಮೊದಲು ಪರಿಶೀಲಿಸಿ",
    supports_claim: "✓ ಸಾಕ್ಷ್ಯವು ಬೆಂಬಲಿಸುತ್ತದೆ",
    contradicts_claim: "❌ ಸಾಕ್ಷ್ಯವು ನಿರಾಕರಿಸುತ್ತದೆ",
    inconclusive_claim: "⚠ ಸಂಬಂಧಿಸಿದೆ / ಅಪೂರ್ಣ ಮಾಹಿತಿ",
    no_sources_found: "ಈ ಸಂದೇಶಕ್ಕೆ ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಪರ್ಯಾಪ್ತ ಪೂರಕ ಸಾಕ್ಷ್ಯಗಳು ಲಭ್ಯವಿಲ್ಲ.",
    upload_another: "ಮತ್ತೊಂದು ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    not_relevant_title: "⚠️ ಪರಿಶೀಲಿಸಲು ಸೂಕ್ತವಾಗಿಲ್ಲ",
    not_relevant_msg: "ಈ ವಿಷಯದಲ್ಲಿ ಯಾವುದೇ ಪರಿಶೀಲಿಸಬಹುದಾದ ಸುದ್ದಿ ಅಥವಾ ಸಂದೇಶ ಕಂಡುಬಂದಿಲ್ಲ.",
    try_another_btn: "ಮತ್ತೊಂದನ್ನು ಪ್ರಯತ್ನಿಸಿ",
    risk_indicators_title: "ಅಪಾಯದ ಸೂಚನೆಗಳು",
    link_check_title: "🔗 ಲಿಂಕ್ ಪರಿಶೀಲನೆ",
    topics: {
      "Health / Medical": "ಆರೋಗ್ಯ / ವೈದ್ಯಕೀಯ",
      "Weather / Advisory": "ಹವಾಮಾನ / ಎಚ್ಚರಿಕೆ",
      "Financial Scam / Viral": "ಹಣಕಾಸು ವಂಚನೆ / ವೈರಲ್",
      "Education": "ಶಿಕ್ಷಣ",
      "Science / Astronomy": "ವಿಜ್ಞಾನ / ಖಗೋಳಶಾಸ್ತ್ರ",
      "Government / Public Policy": "ಸರ್ಕಾರ / ಸಾರ್ವಜನಿಕ ನೀತಿ",
      "Entertainment": "ಮನರಂಜನೆ",
      "Technology / Security": "ತಂತ್ರಜ್ಞಾನ / ಭದ್ರತೆ",
      "General Viral Claim": "ಸಾಧಾರಣ ಪೋಸ್ಟ್",
      "Not Relevant": "ಪರಿಶೀಲಿಸಲು ಸೂಕ್ತವಾಗಿಲ್ಲ"
    }
  },

  Tamil: {
    trust_engine: "வெரிட்டி AI டிரஸ்ட் இன்ஜின்",
    detected_language: "கண்டறியப்பட்ட மொழி",
    response_language: "பதில் மொழி",
    evidence_trust_score: "சான்றுகளின் நம்பகத்தன்மை மதிப்பெண்",
    message_analysis: "செய்தி பகுப்பாய்வு",
    original_input: "அசல் உரை",
    why_header: "இந்தக் கணிப்பின் காரணம் என்ன?",
    why_short: "ஏன்?",
    recommended_action: "நீங்கள் என்ன செய்ய வேண்டும்?",
    evidence_and_sources: "சான்றுகள் மற்றும் ஆதாரங்கள்",
    sources_checked: "சரிபார்க்கப்பட்டது",
    listen: "கேளுங்கள்",
    stop_voice: "நிறுத்து",
    voice_active: "குரல் சேவை உள்ளது",
    voice_unavailable: "குரல் சேவை இல்லை",
    verify_another: "மற்றொரு தகவலைச் சரிபார்க்கவும்",
    topic: "தலைப்பு",
    before_you_share_title: "பகிர்வதற்கு முன் சரிபார்க்கவும்",
    supports_claim: "✓ தகவலை உறுதிப்படுத்துகிறது",
    contradicts_claim: "❌ தகவலை மறுக்கிறது",
    inconclusive_claim: "⚠ தொடர்புடையது / அரைகுறை தகவல்",
    no_sources_found: "இந்த செய்திக்கு இணையத்தில் போதுமான சான்றுகள் கிடைக்கவில்லை.",
    upload_another: "மற்றொரு படத்தை பதிவேற்றவும்",
    not_relevant_title: "⚠️ தொடர்பற்ற தகவல்",
    not_relevant_msg: "இந்தத் தகவலில் சரிபார்க்கக்கூடிய செய்தி எதுவும் கண்டறியப்படவில்லை.",
    try_another_btn: "மற்றொன்றை முயற்சிக்கவும்",
    risk_indicators_title: "ஆபத்து குறிகாட்டிகள்",
    link_check_title: "🔗 இணைப்பு சரிபார்ப்பு",
    topics: {
      "Health / Medical": "சுகாதாரம் / மருத்துவம்",
      "Weather / Advisory": "வானிலை / எச்சரிக்கை",
      "Financial Scam / Viral": "நிதி மோசடி / வைரல்",
      "Education": "கல்வி",
      "Science / Astronomy": "அறிவியல் / வானியல்",
      "Government / Public Policy": "அரசு / பொதுக் கொள்கை",
      "Entertainment": "திரைப்படம் / வினோதம்",
      "Technology / Security": "தொழில்நுட்பம் / பாதுகாப்பு",
      "General Viral Claim": "பொதுவான செய்தி",
      "Not Relevant": "தொடர்பற்ற தகவல்"
    }
  },

  Hindi: {
    trust_engine: "वेरिटी AI ट्रस्ट इंजन",
    detected_language: "पहचानी गई भाषा",
    response_language: "उत्तर की भाषा",
    evidence_trust_score: "प्रमाण विश्वसनीयता स्कोर",
    message_analysis: "संदेश विश्लेषण",
    original_input: "मूल संदेश",
    why_header: "यह आकलन क्यों?",
    why_short: "क्यों?",
    recommended_action: "आपको क्या करना चाहिए?",
    evidence_and_sources: "साक्ष्य और स्रोत",
    sources_checked: "जांच की गई",
    listen: "सुनें",
    stop_voice: "रोकें",
    voice_active: "आवाज उपलब्ध है",
    voice_unavailable: "आवाज उपलब्ध नहीं है",
    verify_another: "दूसरी सामग्री की जांच करें",
    topic: "विषय",
    before_you_share_title: "शेयर करने से पहले जांचें",
    supports_claim: "✓ सूचना का समर्थन करता है",
    contradicts_claim: "❌ सूचना का खंडन करता है",
    inconclusive_claim: "⚠ संबंधित / अपूर्ण साक्ष्य",
    no_sources_found: "इस संदेश के लिए ऑनलाइन पर्याप्त साक्ष्य नहीं मिले।",
    upload_another: "दूसरी छवि अपलोड करें",
    not_relevant_title: "⚠️ प्रासंगिक नहीं है",
    not_relevant_msg: "इस सामग्री में कोई जांच योग्य संदेश नहीं पाया गया।",
    try_another_btn: "दूसरा प्रयास करें",
    risk_indicators_title: "जोखिम संकेत",
    link_check_title: "🔗 लिंक जांच (Link Check)",
    topics: {
      "Health / Medical": "स्वास्थ्य / चिकित्सा",
      "Weather / Advisory": "मौसम / चेतावनी",
      "Financial Scam / Viral": "वित्तीय धोखाधड़ी / वायरल",
      "Education": "शिक्षा",
      "Science / Astronomy": "विज्ञान / खगोल विज्ञान",
      "Government / Public Policy": "सरकार / सार्वजनिक नीति",
      "Entertainment": "मनोरंजन / सिनेमा",
      "Technology / Security": "प्रौद्योगिकी / सुरक्षा",
      "General Viral Claim": "सामान्य संदेश",
      "Not Relevant": "प्रासंगिक नहीं है"
    }
  }
};

export const getTranslation = (lang, key) => {
  const dictionary = UI_TRANSLATIONS[lang] || UI_TRANSLATIONS['English'];
  return dictionary[key] || UI_TRANSLATIONS['English'][key] || key;
};

export const getLocalizedTopic = (lang, topicName) => {
  const dictionary = UI_TRANSLATIONS[lang] || UI_TRANSLATIONS['English'];
  const topicMap = dictionary.topics || UI_TRANSLATIONS['English'].topics;
  return topicMap[topicName] || topicName;
};
